// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE(256, GGML_TYPE_NVFP4, GGML_TYPE_NVFP4);
DECL_FATTN_VEC_CASE_V(512, 256, GGML_TYPE_NVFP4, GGML_TYPE_NVFP4);
